services:
  - type: web
    name: metabase
    env: docker
    plan: free
    autoDeploy: true
    startCommand: java $JAVA_OPTS -jar /app/metabase.jar
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx256m -Xms256m"
    ports:
      - port: 3000
